spring:
  cloud:
    gateway:
      rewrite-to-polymerization:
        enable: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: discovery_
      routes:
        - id: swagger
          uri: lb://swagger
          predicates:
            - Path=/swagger-ui.html,/webjars/springfox-swagger-ui/**,/swagger-resources/**
      gray:
        version-key: #版本号控制header
logging:
  level:
    net.guerlab.smart.platform.basic.gateway: INFO
