spring:
  cloud:
    debug:
      enable: false
      gateway-proxy-url: http://gateway/proxy/
      proxy-header-name: GUERLAB-PROXY
      proxy-header-value: GUERLAB-PROXY
      local-services:
    sentinel:
      scg:
        enabled: true
    gateway:
      rewrite-to-polymerization: #聚合服务
        enable: false #是否启用
        service-names: polymerization-web #聚合目标
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: discovery_
          include-expression: ((!serviceId.endsWith('-api')) && (!serviceId.endsWith('-internal')))
      routes:
        - id: swagger
          uri: lb://swagger
          predicates:
            - Path=/swagger-ui.html,/webjars/springfox-swagger-ui/**,/swagger-resources/**
      gray:
        version-key: #版本号控制header
logging:
  level:
    net.guerlab.smart.platform.basic.gateway: INFO
