server:
  forward-headers-strategy: framework
spring:
  messages:
    basename: messages/*
  jackson:
    serialization:
      fail-on-empty-beans: false
      order-map-entries-by-keys: true
      write-char-arrays-as-json-arrays: true
      write-bigdecimal-as-plain: true
    deserialization:
      fail-on-unknown-properties: false
      fail-on-invalid-subtype: false
    mapper:
      sort-properties-alphabetically: true
    default-property-inclusion: non_null
    format:
      format-long-class: true
      format-long-type: true
      format-float-class: true
      format-float-type: true
      format-double-class: true
      format-double-type: true
  http:
    encoding:
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  i18n:
    default-locale: zh_CN
    locale-change-interceptor:
      param-name: lang
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  sleuth:
    sampler:
      probability: 1
  cloud:
    loadbalancer:
      stats:
        micrometer:
          enabled: false
      version-control:
        enabled: true
      cluster-same:
        enabled: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 60000
            read-timeout: 60000
      compression:
        request:
          enabled: false
        response:
          enabled: false
      httpclient:
        connection-timeout: 60000
        connection-timer-repeat: 60000
        disable-ssl-validation: true
    debug:
      enable: false
      gateway-proxy-url: http://gateway/proxy/
      proxy-header-name: GUERLAB-API-DEBUG-PROXY
      proxy-header-value: GUERLAB-API-DEBUG-PROXY
    sentinel:
      enabled: false
      eager: true
      transport:
        dashboard: sentinel:8080
  global-exception:
    stack-trace-excludes:
      - java
      - jdk.internal
      - javax.servlet
      - org.springframework
      - io.undertow
      - org.jboss
      - feign
      - com.sun
    stack-trace-includes:
      - java.lang
    log-ignore-paths:
      - path: /favicon.ico
  security:
    actuator:
      enabled: true
    user:
      name: ##用户名
      password: ##密码
web:
  cors:
    enable: true
    allow-credentials: true
    allowed-headers: "*"
    allowed-methods: "*"
    allowed-origin-patterns: "*"
    max-age: 1800
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
openapi:
  components:
    security-schemes:
      Authorization:
        type: APIKEY
        name: Authorization
        in: HEADER
  servers:
    - url: http://localhost:${server.port}/
      description: dev
    - url: https://gateway/${spring.application.name}/
      description: test
logging:
  level:
    root: ERROR
    com.netflix: 'OFF'
    com.sun: 'OFF'
    freemarker: 'OFF'
    javax.xml.bind: 'OFF'
    org.apache: 'OFF'
    org.hibernate: 'OFF'
    springfox: 'OFF'
    io.undertow: 'OFF'
    net.guerlab.cloud: INFO
