swagger:
  enable: true
  resources:
    commons-user:
      name: commons-user
      path: commons
      group: commons-user
    user-commons:
      name: user-commons
      path: user
      group: user-commons
    user-user:
      name: user-user
      path: user
      group: user-user
